project:
  type: website
  output-dir: docs

website:
  title: "LASER"
  navbar:
    logo: img/laser-logo-solidbackground.png
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - research.qmd
      - href: conferences.qmd
        text: "Conferences & Workshops"
      - publications.qmd
      - photo-gallery.qmd
    right:
      - about.qmd


format:
  html:
    theme: 
    - flatly
    - "assets/theme.scss"
    backgroundcolor: "#f7f7ff"
    mainfont: "Lato"
    fontcolor: "#1a0933"
    css: styles.css
    toc: true
    header-includes: |
      <script src="https://kit.fontawesome.com/e5da75ca36.js" crossorigin="anonymous"></script>
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400;1,700&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">

editor: source

